import React from 'react'

const AboutSection = () => {
  return (
    <div>
      <h1>À PROPOS</h1>
      <div>
        <h2>PARCOURS</h2>
        <p>DIPLÔMÉ DE L’EDHEC BUSINESS SCHOOL PASSÉ PAR LE SECTEUR DU CONSEIL AVEC SOPRA STERIA PUIS DELOITTE, JE SUIS DEVENU DÉVELOPPEUR WEB POUR LIBÉRER MA CRÉATIVITÉ.</p>
      </div>
      <div>
        <h2>MÉTHODE</h2>
        <p>DIPLÔMÉ DE L’EDHEC BUSINESS SCHOOL PASSÉ PAR LE SECTEUR DU CONSEIL AVEC SOPRA STERIA PUIS DELOITTE, JE SUIS DEVENU DÉVELOPPEUR WEB POUR LIBÉRER MA CRÉATIVITÉ.</p>
      </div>
      <div>
        <h2>APTITUDES</h2>
        <p>DIPLÔMÉ DE L’EDHEC BUSINESS SCHOOL PASSÉ PAR LE SECTEUR DU CONSEIL AVEC SOPRA STERIA PUIS DELOITTE, JE SUIS DEVENU DÉVELOPPEUR WEB POUR LIBÉRER MA CRÉATIVITÉ.</p>
      </div>
    </div>
  )
}

export default AboutSection
